=== MatejaMaric/NRT_12_19/oglasi.dtd
<!ELEMENT Oglasi (Oglas+)>
<!ELEMENT Oglas (Kategorija, DatumIsteka, Cena, Tekst, Oznake, EmailAdrese)>

<!ELEMENT Kategorija EMPTY>
<!ELEMENT DatumIsteka (#PCDATA)>
<!ELEMENT Cena (#PCDATA)>
<!ELEMENT Tekst (#PCDATA)>

<!ELEMENT Oznake (Oznaka+)>
<!ELEMENT EmailAdrese (Email+)>

<!ELEMENT Oznaka (#PCDATA)>
<!ELEMENT Email (#PCDATA)>

<!ATTLIST Kategorija naziv (automobili|stanovi|laptopovi) #REQUIRED>
<!ATTLIST Cena valuta (RSD|EUR) #REQUIRED>
<!ATTLIST Oznaka tip CDATA #REQUIRED>
<!ATTLIST Email tip (sluzbeni|privatni) #REQUIRED>

=== MatejaMaric/NRT_12_19/oglasi.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Oglasi SYSTEM "oglasi.dtd">
<Oglasi>
    <Oglas>
        <Kategorija naziv="nekretnine" />
        <DatumIsteka>2022-09-18</DatumIsteka>
        <Cena valuta="EUR">70000</Cena>
        <Tekst>Stan u Vojvode Stepe</Tekst>
        <Oznake>
          <Oznaka tip="velicina">50m2</Oznaka>
        </Oznake>
        <EmailAdrese>
          <Email email="privatni">pera@zdera.rs</Email>
        </EmailAdrese>
    </Oglas>
    <Oglas>
        <Kategorija>Laptopovi</Kategorija>
        <DatumIsteka>2022-07-14</DatumIsteka>
        <Cena valuta="EUR">200</Cena>
        <Tekst>ThinkPad X220</Tekst>
        <Oznake>
          <Oznaka tip="rezolucina">1280x720</Oznaka>
        </Oznake>
        <EmailAdrese>
          <Email tip="privatni">pera@zdera.rs</Email>
        </EmailAdrese>
    </Oglas>
</Oglasi>
